# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fly/fly/exeSocket

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fly/fly/exeSocket

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fly/fly/exeSocket/CMakeFiles /home/fly/fly/exeSocket//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fly/fly/exeSocket/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named exesocket

# Build rule for target.
exesocket: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exesocket
.PHONY : exesocket

# fast build rule for target.
exesocket/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/build
.PHONY : exesocket/fast

src/Data.o: src/Data.cpp.o

.PHONY : src/Data.o

# target to build an object file
src/Data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Data.cpp.o
.PHONY : src/Data.cpp.o

src/Data.i: src/Data.cpp.i

.PHONY : src/Data.i

# target to preprocess a source file
src/Data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Data.cpp.i
.PHONY : src/Data.cpp.i

src/Data.s: src/Data.cpp.s

.PHONY : src/Data.s

# target to generate assembly for a file
src/Data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Data.cpp.s
.PHONY : src/Data.cpp.s

src/Epoll.o: src/Epoll.cpp.o

.PHONY : src/Epoll.o

# target to build an object file
src/Epoll.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Epoll.cpp.o
.PHONY : src/Epoll.cpp.o

src/Epoll.i: src/Epoll.cpp.i

.PHONY : src/Epoll.i

# target to preprocess a source file
src/Epoll.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Epoll.cpp.i
.PHONY : src/Epoll.cpp.i

src/Epoll.s: src/Epoll.cpp.s

.PHONY : src/Epoll.s

# target to generate assembly for a file
src/Epoll.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Epoll.cpp.s
.PHONY : src/Epoll.cpp.s

src/Server.o: src/Server.cpp.o

.PHONY : src/Server.o

# target to build an object file
src/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Server.cpp.o
.PHONY : src/Server.cpp.o

src/Server.i: src/Server.cpp.i

.PHONY : src/Server.i

# target to preprocess a source file
src/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Server.cpp.i
.PHONY : src/Server.cpp.i

src/Server.s: src/Server.cpp.s

.PHONY : src/Server.s

# target to generate assembly for a file
src/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Server.cpp.s
.PHONY : src/Server.cpp.s

src/Socket.o: src/Socket.cpp.o

.PHONY : src/Socket.o

# target to build an object file
src/Socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Socket.cpp.o
.PHONY : src/Socket.cpp.o

src/Socket.i: src/Socket.cpp.i

.PHONY : src/Socket.i

# target to preprocess a source file
src/Socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Socket.cpp.i
.PHONY : src/Socket.cpp.i

src/Socket.s: src/Socket.cpp.s

.PHONY : src/Socket.s

# target to generate assembly for a file
src/Socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Socket.cpp.s
.PHONY : src/Socket.cpp.s

src/ThreadPool.o: src/ThreadPool.cpp.o

.PHONY : src/ThreadPool.o

# target to build an object file
src/ThreadPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/ThreadPool.cpp.o
.PHONY : src/ThreadPool.cpp.o

src/ThreadPool.i: src/ThreadPool.cpp.i

.PHONY : src/ThreadPool.i

# target to preprocess a source file
src/ThreadPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/ThreadPool.cpp.i
.PHONY : src/ThreadPool.cpp.i

src/ThreadPool.s: src/ThreadPool.cpp.s

.PHONY : src/ThreadPool.s

# target to generate assembly for a file
src/ThreadPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/ThreadPool.cpp.s
.PHONY : src/ThreadPool.cpp.s

src/Util.o: src/Util.cpp.o

.PHONY : src/Util.o

# target to build an object file
src/Util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Util.cpp.o
.PHONY : src/Util.cpp.o

src/Util.i: src/Util.cpp.i

.PHONY : src/Util.i

# target to preprocess a source file
src/Util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Util.cpp.i
.PHONY : src/Util.cpp.i

src/Util.s: src/Util.cpp.s

.PHONY : src/Util.s

# target to generate assembly for a file
src/Util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/Util.cpp.s
.PHONY : src/Util.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exesocket.dir/build.make CMakeFiles/exesocket.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... exesocket"
	@echo "... src/Data.o"
	@echo "... src/Data.i"
	@echo "... src/Data.s"
	@echo "... src/Epoll.o"
	@echo "... src/Epoll.i"
	@echo "... src/Epoll.s"
	@echo "... src/Server.o"
	@echo "... src/Server.i"
	@echo "... src/Server.s"
	@echo "... src/Socket.o"
	@echo "... src/Socket.i"
	@echo "... src/Socket.s"
	@echo "... src/ThreadPool.o"
	@echo "... src/ThreadPool.i"
	@echo "... src/ThreadPool.s"
	@echo "... src/Util.o"
	@echo "... src/Util.i"
	@echo "... src/Util.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

